-- =============================================================================
-- Mobile Repair Shop SaaS — Consolidated PostgreSQL Schema
-- Generated by concatenating the numbered migration files (01..22) in order.
-- Apply with:
--   psql -h <host> -U <user> -d <db> -f schema.sql
-- =============================================================================


-- #############################################################################
-- 01_schema.sql
-- #############################################################################
-- =============================================================================
-- Mobile Repair Shop SaaS — PostgreSQL Schema
-- Multi-tenant, UUID PKs, created_at/updated_at, proper FKs
-- =============================================================================

-- Extend PostgreSQL to generate UUIDs
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =============================================================================
-- TENANT & IDENTITY
-- =============================================================================

CREATE TABLE shops (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name            VARCHAR(255) NOT NULL,
    slug            VARCHAR(100) NOT NULL UNIQUE,
    email           VARCHAR(255),
    phone           VARCHAR(50),
    address         TEXT,
    timezone        VARCHAR(50) DEFAULT 'Asia/Kolkata',
    is_active       BOOLEAN DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE users (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    shop_id         UUID NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    email           VARCHAR(255) NOT NULL,
    password_hash   VARCHAR(255),
    name            VARCHAR(255),
    role            VARCHAR(50) NOT NULL,  -- 'SHOP_OWNER' | 'TECHNICIAN' | 'SUPER_ADMIN'
    is_active       BOOLEAN DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (shop_id, email)
);

CREATE INDEX idx_users_shop_id ON users(shop_id);
CREATE INDEX idx_users_email ON users(email);

-- =============================================================================
-- SUBSCRIPTIONS (referenced by shops)
-- =============================================================================

CREATE TABLE subscriptions (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    shop_id         UUID NOT NULL REFERENCES shops(id) ON DELETE CASCADE UNIQUE,
    plan_code       VARCHAR(50) NOT NULL,   -- 'STARTER' | 'PRO' | 'ENTERPRISE'
    status          VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',  -- 'TRIAL' | 'ACTIVE' | 'PAST_DUE' | 'CANCELLED'
    started_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    current_period_end TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_subscriptions_shop_id ON subscriptions(shop_id);
CREATE INDEX idx_subscriptions_status ON subscriptions(status);

-- =============================================================================
-- TECHNICIANS & CUSTOMERS
-- =============================================================================

CREATE TABLE technicians (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    shop_id         UUID NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    user_id         UUID REFERENCES users(id) ON DELETE SET NULL,
    name            VARCHAR(255) NOT NULL,
    email           VARCHAR(255),
    phone           VARCHAR(50),
    role_label      VARCHAR(100),          -- e.g. 'Senior Technician'
    is_available    BOOLEAN DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_technicians_shop_id ON technicians(shop_id);
CREATE INDEX idx_technicians_user_id ON technicians(user_id);

CREATE TABLE customers (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    shop_id         UUID NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    name            VARCHAR(255) NOT NULL,
    email           VARCHAR(255),
    phone           VARCHAR(50) NOT NULL,
    address         TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_customers_shop_id ON customers(shop_id);
CREATE INDEX idx_customers_phone ON customers(shop_id, phone);

-- =============================================================================
-- MASTER DATA (platform-wide; optional shop_id for shop-specific overrides)
-- =============================================================================

CREATE TABLE master_brands (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name            VARCHAR(100) NOT NULL UNIQUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE master_models (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    brand_id        UUID NOT NULL REFERENCES master_brands(id) ON DELETE CASCADE,
    name            VARCHAR(255) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (brand_id, name)
);

CREATE INDEX idx_master_models_brand_id ON master_models(brand_id);

CREATE TABLE master_ram_options (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    value_gb        INT NOT NULL UNIQUE,    -- 4, 6, 8, 12, 16, etc.
    label           VARCHAR(20) NOT NULL,    -- '4 GB', '8 GB'
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE master_storage_options (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    value_gb        INT NOT NULL UNIQUE,
    label           VARCHAR(20) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE master_repair_services (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code            VARCHAR(50) NOT NULL UNIQUE,
    name            VARCHAR(255) NOT NULL,
    description     TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =============================================================================
-- TICKETS (REPAIR)
-- =============================================================================

CREATE TABLE tickets (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    shop_id             UUID NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    customer_id         UUID NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
    customer_name       VARCHAR(200),
    customer_phone      VARCHAR(30),
    assigned_technician_id UUID REFERENCES technicians(id) ON DELETE SET NULL,
    tracking_id         VARCHAR(50) NOT NULL,
    brand_id            UUID REFERENCES master_brands(id) ON DELETE SET NULL,
    model_id            UUID REFERENCES master_models(id) ON DELETE SET NULL,
    ram_option_id       UUID REFERENCES master_ram_options(id) ON DELETE SET NULL,
    storage_option_id  UUID REFERENCES master_storage_options(id) ON DELETE SET NULL,
    color               VARCHAR(100),
    imei                VARCHAR(50),
    status              VARCHAR(50) NOT NULL DEFAULT 'CREATED',  -- CREATED, IN_DIAGNOSIS, QUOTED, APPROVED, IN_REPAIR, READY, DELIVERED, CANCELLED
    estimated_price     DECIMAL(12, 2),
    final_price         DECIMAL(12, 2),
    issue_description  TEXT,
    device_display_name VARCHAR(200),
    device_image_url    VARCHAR(1000),
    repair_services_summary VARCHAR(500),
    price_items_json    TEXT,
    missing_parts_json  TEXT,
    device_photos_json  TEXT,
    device_security_type VARCHAR(20),
    device_security_value VARCHAR(255),
    customer_approval   BOOLEAN,
    estimated_ready_at  TIMESTAMPTZ,
    estimated_delivery_at TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (shop_id, tracking_id)
);

CREATE INDEX idx_tickets_shop_id ON tickets(shop_id);
CREATE INDEX idx_tickets_customer_id ON tickets(customer_id);
CREATE INDEX idx_tickets_customer_phone ON tickets(shop_id, customer_phone);
CREATE INDEX idx_tickets_status ON tickets(shop_id, status);
CREATE INDEX idx_tickets_tracking_id ON tickets(shop_id, tracking_id);
CREATE INDEX idx_tickets_created_at ON tickets(shop_id, created_at DESC);

CREATE TABLE ticket_status_history (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ticket_id       UUID NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
    from_status     VARCHAR(50),
    to_status       VARCHAR(50) NOT NULL,
    changed_by_id   UUID REFERENCES users(id) ON DELETE SET NULL,
    note            TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_ticket_status_history_ticket_id ON ticket_status_history(ticket_id);

CREATE TABLE repair_notes (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ticket_id       UUID NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
    author_id       UUID REFERENCES users(id) ON DELETE SET NULL,
    note            TEXT NOT NULL,
    is_internal     BOOLEAN DEFAULT false,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_repair_notes_ticket_id ON repair_notes(ticket_id);

-- =============================================================================
-- PICKUP REQUESTS
-- =============================================================================

CREATE TABLE pickup_requests (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    shop_id         UUID NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    ticket_id       UUID REFERENCES tickets(id) ON DELETE SET NULL,
    customer_id     UUID NOT NULL REFERENCES customers(id) ON DELETE RESTRICT,
    type            VARCHAR(50) NOT NULL,   -- 'PICKUP' | 'DELIVERY'
    scheduled_slot  TIMESTAMPTZ,
    address         TEXT,
    status          VARCHAR(50) NOT NULL DEFAULT 'REQUESTED',  -- REQUESTED, SCHEDULED, IN_TRANSIT, COMPLETED, CANCELLED
    completed_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_pickup_requests_shop_id ON pickup_requests(shop_id);
CREATE INDEX idx_pickup_requests_ticket_id ON pickup_requests(ticket_id);
CREATE INDEX idx_pickup_requests_customer_id ON pickup_requests(customer_id);
CREATE INDEX idx_pickup_requests_status ON pickup_requests(shop_id, status);

-- =============================================================================
-- INVENTORY
-- =============================================================================

CREATE TABLE inventory_items (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    shop_id         UUID NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    sku             VARCHAR(100),
    name            VARCHAR(255) NOT NULL,
    category        VARCHAR(100),          -- 'PART' | 'ACCESSORY' | 'CONSUMABLE'
    quantity        INT NOT NULL DEFAULT 0 CHECK (quantity >= 0),
    unit_price      DECIMAL(12, 2),
    reorder_level   INT DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (shop_id, sku)
);

CREATE INDEX idx_inventory_items_shop_id ON inventory_items(shop_id);
CREATE INDEX idx_inventory_items_category ON inventory_items(shop_id, category);

-- =============================================================================
-- MARKETPLACE (BUY/SELL)
-- =============================================================================

CREATE TABLE marketplace_products (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    shop_id         UUID NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    brand_id        UUID REFERENCES master_brands(id) ON DELETE SET NULL,
    model_id        UUID REFERENCES master_models(id) ON DELETE SET NULL,
    title           VARCHAR(255) NOT NULL,
    description     TEXT,
    type            VARCHAR(50) NOT NULL,   -- 'SELL' | 'BUY'
    price           DECIMAL(12, 2),
    status          VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',  -- DRAFT, ACTIVE, SOLD, INACTIVE
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_marketplace_products_shop_id ON marketplace_products(shop_id);
CREATE INDEX idx_marketplace_products_type ON marketplace_products(shop_id, type);
CREATE INDEX idx_marketplace_products_status ON marketplace_products(shop_id, status);

CREATE TABLE marketplace_orders (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    shop_id         UUID NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    customer_id     UUID REFERENCES customers(id) ON DELETE SET NULL,
    order_number    VARCHAR(50) NOT NULL,
    status          VARCHAR(50) NOT NULL DEFAULT 'PENDING',  -- PENDING, CONFIRMED, PAID, SHIPPED, DELIVERED, CANCELLED
    total_amount    DECIMAL(12, 2) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (shop_id, order_number)
);

CREATE INDEX idx_marketplace_orders_shop_id ON marketplace_orders(shop_id);
CREATE INDEX idx_marketplace_orders_customer_id ON marketplace_orders(customer_id);

CREATE TABLE marketplace_order_items (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id        UUID NOT NULL REFERENCES marketplace_orders(id) ON DELETE CASCADE,
    product_id      UUID NOT NULL REFERENCES marketplace_products(id) ON DELETE RESTRICT,
    quantity        INT NOT NULL DEFAULT 1 CHECK (quantity > 0),
    unit_price      DECIMAL(12, 2) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_marketplace_order_items_order_id ON marketplace_order_items(order_id);

-- =============================================================================
-- SALES HISTORY (aggregated / audit for billing & reporting)
-- =============================================================================

CREATE TABLE sales_history (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    shop_id         UUID NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    source          VARCHAR(50) NOT NULL,   -- 'REPAIR' | 'MARKETPLACE'
    source_id       UUID NOT NULL,          -- ticket_id or order_id
    amount          DECIMAL(12, 2) NOT NULL,
    sale_date       DATE NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_sales_history_shop_id ON sales_history(shop_id);
CREATE INDEX idx_sales_history_sale_date ON sales_history(shop_id, sale_date DESC);
CREATE INDEX idx_sales_history_source ON sales_history(shop_id, source);

-- =============================================================================
-- UPDATED_AT TRIGGER
-- =============================================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply updated_at trigger to each table (use EXECUTE PROCEDURE for PG 10; EXECUTE FUNCTION for PG 11+)
CREATE TRIGGER trg_shops_updated_at BEFORE UPDATE ON shops FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_technicians_updated_at BEFORE UPDATE ON technicians FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_customers_updated_at BEFORE UPDATE ON customers FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_subscriptions_updated_at BEFORE UPDATE ON subscriptions FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_master_brands_updated_at BEFORE UPDATE ON master_brands FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_master_models_updated_at BEFORE UPDATE ON master_models FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_master_ram_options_updated_at BEFORE UPDATE ON master_ram_options FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_master_storage_options_updated_at BEFORE UPDATE ON master_storage_options FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_master_repair_services_updated_at BEFORE UPDATE ON master_repair_services FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_tickets_updated_at BEFORE UPDATE ON tickets FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_repair_notes_updated_at BEFORE UPDATE ON repair_notes FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_pickup_requests_updated_at BEFORE UPDATE ON pickup_requests FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_inventory_items_updated_at BEFORE UPDATE ON inventory_items FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_marketplace_products_updated_at BEFORE UPDATE ON marketplace_products FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_marketplace_orders_updated_at BEFORE UPDATE ON marketplace_orders FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_marketplace_order_items_updated_at BEFORE UPDATE ON marketplace_order_items FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_sales_history_updated_at BEFORE UPDATE ON sales_history FOR EACH ROW EXECUTE PROCEDURE set_updated_at();


-- #############################################################################
-- 02_customer_app.sql
-- #############################################################################
-- =============================================================================
-- Mobile Repair Shop SaaS — Customer App Schema (Phase 2)
-- Adds platform-wide customer profile, addresses, saved devices, extended
-- master data, shop directory, pickup orders, unified orders, marketplace, etc.
-- =============================================================================

-- =============================================================================
-- PLATFORM-WIDE CUSTOMER IDENTITY
-- =============================================================================

CREATE TABLE customer_users (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    full_name           VARCHAR(255),
    email               VARCHAR(255) UNIQUE,
    mobile              VARCHAR(50) UNIQUE,
    alternate_mobile    VARCHAR(50),
    profile_image_url   VARCHAR(500),
    id_proof_url        VARCHAR(1000),
    password_hash       VARCHAR(255),
    is_active           BOOLEAN DEFAULT true,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_customer_users_email ON customer_users(email);
CREATE INDEX idx_customer_users_mobile ON customer_users(mobile);

CREATE TABLE customer_addresses (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_user_id    UUID NOT NULL REFERENCES customer_users(id) ON DELETE CASCADE,
    label               VARCHAR(50) NOT NULL DEFAULT 'Home',
    full_name           VARCHAR(255),
    mobile              VARCHAR(50),
    pincode             VARCHAR(20),
    locality            VARCHAR(255), -- LEGACY: prefer area. API dual-writes area -> locality for back-compat readers.
    area                VARCHAR(255), -- shown as "Area" in the customer-app form
    address_line        TEXT,         -- shown as "Door no. / Street" in the customer-app form
    city                VARCHAR(255), -- LEGACY: prefer district. API dual-writes district -> city for back-compat readers.
    district            VARCHAR(255),
    taluk               VARCHAR(255),
    state               VARCHAR(255),
    latitude            DECIMAL(10, 7),
    longitude           DECIMAL(10, 7),
    is_default          BOOLEAN DEFAULT false,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_customer_addresses_user ON customer_addresses(customer_user_id);

CREATE TABLE customer_saved_devices (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_user_id    UUID NOT NULL REFERENCES customer_users(id) ON DELETE CASCADE,
    category_id         UUID,
    brand_id            UUID,
    model_id            UUID,
    ram_option_id       UUID,
    storage_option_id   UUID,
    color               VARCHAR(100),
    imei                VARCHAR(50),
    note                TEXT,
    is_default          BOOLEAN DEFAULT false,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_customer_saved_devices_user ON customer_saved_devices(customer_user_id);

ALTER TABLE customer_saved_devices ADD COLUMN IF NOT EXISTS category_code VARCHAR(50);
ALTER TABLE customer_saved_devices ADD COLUMN IF NOT EXISTS model_name    VARCHAR(255);
ALTER TABLE customer_saved_devices ADD COLUMN IF NOT EXISTS brand_name    VARCHAR(150);
ALTER TABLE customer_saved_devices ADD COLUMN IF NOT EXISTS ram_label     VARCHAR(50);
ALTER TABLE customer_saved_devices ADD COLUMN IF NOT EXISTS storage_label VARCHAR(50);

-- =============================================================================
-- EXTENDED MASTER DATA
-- =============================================================================

CREATE TABLE master_device_categories (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code            VARCHAR(50) NOT NULL UNIQUE,
    name            VARCHAR(100) NOT NULL,
    image_url       VARCHAR(500),
    image_base64    TEXT,
    sort_order      INT NOT NULL DEFAULT 0,
    is_active       BOOLEAN DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE master_models ADD COLUMN IF NOT EXISTS category_id UUID REFERENCES master_device_categories(id) ON DELETE SET NULL;
ALTER TABLE master_models ADD COLUMN IF NOT EXISTS image_url   VARCHAR(500);
ALTER TABLE master_models ADD COLUMN IF NOT EXISTS image_base64 TEXT;
ALTER TABLE master_brands ADD COLUMN IF NOT EXISTS image_url   VARCHAR(500);
ALTER TABLE master_brands ADD COLUMN IF NOT EXISTS image_base64 TEXT;

CREATE TABLE master_device_types (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    category_id     UUID NOT NULL REFERENCES master_device_categories(id) ON DELETE CASCADE,
    code            VARCHAR(80),
    name            VARCHAR(120) NOT NULL,
    image_url       VARCHAR(500),
    image_base64    TEXT,
    sort_order      INT NOT NULL DEFAULT 0,
    is_active       BOOLEAN DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (category_id, name)
);

CREATE INDEX idx_master_device_types_category ON master_device_types(category_id);

CREATE TABLE master_device_series (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    brand_id        UUID NOT NULL REFERENCES master_brands(id) ON DELETE CASCADE,
    name            VARCHAR(100) NOT NULL,
    sort_order      INT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (brand_id, name)
);

CREATE INDEX idx_master_device_series_brand ON master_device_series(brand_id);

ALTER TABLE master_models ADD COLUMN IF NOT EXISTS series_id UUID REFERENCES master_device_series(id) ON DELETE SET NULL;

CREATE TABLE master_colors (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name            VARCHAR(100) NOT NULL UNIQUE,
    hex_code        VARCHAR(20),
    sort_order      INT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE master_model_variants (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    model_id        UUID NOT NULL REFERENCES master_models(id) ON DELETE CASCADE,
    ram_option_id   UUID REFERENCES master_ram_options(id) ON DELETE SET NULL,
    storage_option_id UUID REFERENCES master_storage_options(id) ON DELETE SET NULL,
    color_id        UUID REFERENCES master_colors(id) ON DELETE SET NULL,
    reference_price DECIMAL(12, 2),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_master_model_variants_model ON master_model_variants(model_id);

CREATE TABLE master_repair_categories (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code            VARCHAR(50) NOT NULL UNIQUE,
    name            VARCHAR(255) NOT NULL,
    icon_url        VARCHAR(500),
    icon_base64     TEXT,
    description     TEXT,
    sort_order      INT NOT NULL DEFAULT 0,
    is_active       BOOLEAN DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE master_repair_services ADD COLUMN IF NOT EXISTS category_id UUID REFERENCES master_repair_categories(id) ON DELETE SET NULL;
ALTER TABLE master_repair_services ADD COLUMN IF NOT EXISTS device_category_id UUID REFERENCES master_device_categories(id) ON DELETE SET NULL;
ALTER TABLE master_repair_services ADD COLUMN IF NOT EXISTS icon_url VARCHAR(500);
ALTER TABLE master_repair_services ADD COLUMN IF NOT EXISTS icon_base64 TEXT;

ALTER TABLE master_repair_categories ADD COLUMN IF NOT EXISTS device_category_id UUID REFERENCES master_device_categories(id) ON DELETE CASCADE;
ALTER TABLE master_repair_categories ADD COLUMN IF NOT EXISTS display_name VARCHAR(255);
ALTER TABLE master_repair_categories ALTER COLUMN code TYPE VARCHAR(80);

CREATE TABLE master_screening_questions (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    flow            VARCHAR(50) NOT NULL DEFAULT 'WORKING',
    question        TEXT NOT NULL,
    helper_text     TEXT,
    sort_order      INT NOT NULL DEFAULT 0,
    is_active       BOOLEAN DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_master_screening_questions_flow ON master_screening_questions(flow);

CREATE TABLE master_condition_groups (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code            VARCHAR(100) NOT NULL UNIQUE,
    name            VARCHAR(255) NOT NULL,
    flow            VARCHAR(50) NOT NULL DEFAULT 'COMMON',
    sort_order      INT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE master_condition_options (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    group_id            UUID NOT NULL REFERENCES master_condition_groups(id) ON DELETE CASCADE,
    label               VARCHAR(255) NOT NULL,
    icon_url            VARCHAR(500),
    icon_base64         TEXT,
    price_impact        DECIMAL(12, 2) DEFAULT 0,
    sort_order          INT NOT NULL DEFAULT 0,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_master_condition_options_group ON master_condition_options(group_id);

CREATE TABLE master_functional_issues (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code            VARCHAR(100) NOT NULL UNIQUE,
    name            VARCHAR(255) NOT NULL,
    icon_url        VARCHAR(500),
    icon_base64     TEXT,
    price_impact    DECIMAL(12, 2) DEFAULT 0,
    sort_order      INT NOT NULL DEFAULT 0,
    is_active       BOOLEAN DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE master_accessory_options (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code            VARCHAR(100) NOT NULL UNIQUE,
    name            VARCHAR(255) NOT NULL,
    icon_url        VARCHAR(500),
    icon_base64     TEXT,
    sort_order      INT NOT NULL DEFAULT 0,
    is_active       BOOLEAN DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE master_warranty_options (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code            VARCHAR(50) NOT NULL UNIQUE,
    label           VARCHAR(100) NOT NULL,
    sort_order      INT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE master_banners (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title           VARCHAR(255),
    image_url       VARCHAR(500),
    image_base64    TEXT,
    link_target     VARCHAR(255),
    sort_order      INT NOT NULL DEFAULT 0,
    is_active       BOOLEAN DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE master_faq_items (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    question        TEXT NOT NULL,
    answer          TEXT NOT NULL,
    sort_order      INT NOT NULL DEFAULT 0,
    is_active       BOOLEAN DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE master_app_content (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code            VARCHAR(50) NOT NULL UNIQUE,
    title           VARCHAR(255) NOT NULL,
    body            TEXT,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE master_support_contacts (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    label           VARCHAR(100) NOT NULL,
    email           VARCHAR(255),
    phone           VARCHAR(50),
    image_url       VARCHAR(500),
    sort_order      INT NOT NULL DEFAULT 0,
    is_active       BOOLEAN DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =============================================================================
-- SHOP DIRECTORY
-- =============================================================================

ALTER TABLE shops ADD COLUMN IF NOT EXISTS latitude DECIMAL(10, 7);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS longitude DECIMAL(10, 7);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS city VARCHAR(255);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS state VARCHAR(255);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS pincode VARCHAR(20);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS rating DECIMAL(3, 1);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS hours_text VARCHAR(255);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS hero_image_url VARCHAR(500);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS description TEXT;

CREATE TABLE shop_services (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    shop_id         UUID NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    service_code    VARCHAR(50) NOT NULL,
    is_enabled      BOOLEAN DEFAULT true,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (shop_id, service_code)
);

CREATE TABLE shop_images (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    shop_id         UUID NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    image_url       VARCHAR(500) NOT NULL,
    sort_order      INT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_shop_images_shop ON shop_images(shop_id);

CREATE TABLE shop_pickup_slots (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    shop_id         UUID NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    day_of_week     SMALLINT,
    start_time      TIME NOT NULL,
    end_time        TIME NOT NULL,
    capacity        INT DEFAULT 10,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_shop_pickup_slots_shop ON shop_pickup_slots(shop_id);

-- =============================================================================
-- CUSTOMER-FACING ORDER FLOWS
-- =============================================================================

CREATE TABLE customer_pickup_orders (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_number        VARCHAR(60) NOT NULL UNIQUE,
    customer_user_id    UUID NOT NULL REFERENCES customer_users(id) ON DELETE CASCADE,
    shop_id             UUID REFERENCES shops(id) ON DELETE SET NULL,
    ticket_id           UUID REFERENCES tickets(id) ON DELETE SET NULL,
    address_id          UUID REFERENCES customer_addresses(id) ON DELETE SET NULL,
    flow_type           VARCHAR(50) NOT NULL DEFAULT 'REPAIR_PICKUP',
    pickup_date         DATE,
    pickup_slot_start   TIME,
    pickup_slot_end     TIME,
    status              VARCHAR(50) NOT NULL DEFAULT 'ORDER_PLACED',
    estimate_amount     DECIMAL(12, 2),
    final_amount        DECIMAL(12, 2),
    note                TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_customer_pickup_orders_user ON customer_pickup_orders(customer_user_id);
CREATE INDEX idx_customer_pickup_orders_shop ON customer_pickup_orders(shop_id);
CREATE INDEX idx_customer_pickup_orders_status ON customer_pickup_orders(status);

CREATE TABLE customer_pickup_order_events (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    pickup_order_id     UUID NOT NULL REFERENCES customer_pickup_orders(id) ON DELETE CASCADE,
    status              VARCHAR(100) NOT NULL,
    note                TEXT,
    actor               VARCHAR(100),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_customer_pickup_order_events_order ON customer_pickup_order_events(pickup_order_id);

CREATE TABLE customer_orders (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_number        VARCHAR(60) NOT NULL UNIQUE,
    customer_user_id    UUID NOT NULL REFERENCES customer_users(id) ON DELETE CASCADE,
    shop_id             UUID REFERENCES shops(id) ON DELETE SET NULL,
    order_type          VARCHAR(50) NOT NULL,
    reference_id        UUID,
    status              VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    total_amount        DECIMAL(12, 2),
    payload_json        TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_customer_orders_user ON customer_orders(customer_user_id);
CREATE INDEX idx_customer_orders_type ON customer_orders(order_type);
CREATE INDEX idx_customer_orders_status ON customer_orders(status);

-- =============================================================================
-- SELL ORDERS
-- =============================================================================

CREATE TABLE sell_orders (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sell_number         VARCHAR(60) NOT NULL UNIQUE,
    customer_user_id    UUID NOT NULL REFERENCES customer_users(id) ON DELETE CASCADE,
    shop_id             UUID REFERENCES shops(id) ON DELETE SET NULL,
    address_id          UUID REFERENCES customer_addresses(id) ON DELETE SET NULL,
    brand_id            UUID REFERENCES master_brands(id) ON DELETE SET NULL,
    model_id            UUID REFERENCES master_models(id) ON DELETE SET NULL,
    ram_option_id       UUID REFERENCES master_ram_options(id) ON DELETE SET NULL,
    storage_option_id   UUID REFERENCES master_storage_options(id) ON DELETE SET NULL,
    color               VARCHAR(100),
    imei                VARCHAR(50),
    working_condition   VARCHAR(50),
    warranty_code       VARCHAR(50),
    device_condition_summary TEXT,
    payload_json        TEXT,
    front_image_url     VARCHAR(500),
    back_image_url      VARCHAR(500),
    side_image_url      VARCHAR(500),
    camera_image_url    VARCHAR(500),
    other_image_url     VARCHAR(500),
    status              VARCHAR(50) NOT NULL DEFAULT 'AWAITING_QUOTATION',
    final_price         DECIMAL(12, 2),
    pickup_date         DATE,
    pickup_slot_start   TIME,
    pickup_slot_end     TIME,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_sell_orders_user ON sell_orders(customer_user_id);
CREATE INDEX idx_sell_orders_status ON sell_orders(status);

CREATE TABLE sell_order_screening_answers (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sell_order_id       UUID NOT NULL REFERENCES sell_orders(id) ON DELETE CASCADE,
    question_id         UUID REFERENCES master_screening_questions(id) ON DELETE SET NULL,
    answer              VARCHAR(255),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_sell_order_screening_answers_order ON sell_order_screening_answers(sell_order_id);

CREATE TABLE sell_order_conditions (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sell_order_id       UUID NOT NULL REFERENCES sell_orders(id) ON DELETE CASCADE,
    group_code          VARCHAR(100) NOT NULL,
    option_id           UUID REFERENCES master_condition_options(id) ON DELETE SET NULL,
    option_label        VARCHAR(255),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_sell_order_conditions_order ON sell_order_conditions(sell_order_id);

CREATE TABLE sell_order_issues (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sell_order_id       UUID NOT NULL REFERENCES sell_orders(id) ON DELETE CASCADE,
    issue_id            UUID REFERENCES master_functional_issues(id) ON DELETE SET NULL,
    issue_code          VARCHAR(100),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_sell_order_issues_order ON sell_order_issues(sell_order_id);

CREATE TABLE sell_order_accessories (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sell_order_id       UUID NOT NULL REFERENCES sell_orders(id) ON DELETE CASCADE,
    accessory_id        UUID REFERENCES master_accessory_options(id) ON DELETE SET NULL,
    accessory_code      VARCHAR(100),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_sell_order_accessories_order ON sell_order_accessories(sell_order_id);

CREATE TABLE sell_order_quotations (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sell_order_id       UUID NOT NULL REFERENCES sell_orders(id) ON DELETE CASCADE,
    shop_id             UUID NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    shop_name           VARCHAR(255),
    shop_phone          VARCHAR(50),
    shop_city           VARCHAR(255),
    quotation_price     DECIMAL(12, 2) NOT NULL,
    note                TEXT,
    status              VARCHAR(50) NOT NULL DEFAULT 'PROPOSED',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (sell_order_id, shop_id)
);

CREATE INDEX idx_sell_order_quotations_order ON sell_order_quotations(sell_order_id);

-- =============================================================================
-- REPAIR BOOKINGS
-- =============================================================================

CREATE TABLE repair_bookings (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_number      VARCHAR(60) NOT NULL UNIQUE,
    customer_user_id    UUID NOT NULL REFERENCES customer_users(id) ON DELETE CASCADE,
    customer_name       VARCHAR(255),
    customer_mobile     VARCHAR(50),
    shop_id             UUID REFERENCES shops(id) ON DELETE SET NULL,
    ticket_id           UUID REFERENCES tickets(id) ON DELETE SET NULL,
    assigned_technician_id UUID,
    saved_device_id     UUID REFERENCES customer_saved_devices(id) ON DELETE SET NULL,
    brand_id            UUID REFERENCES master_brands(id) ON DELETE SET NULL,
    model_id            UUID REFERENCES master_models(id) ON DELETE SET NULL,
    ram_option_id       UUID REFERENCES master_ram_options(id) ON DELETE SET NULL,
    storage_option_id   UUID REFERENCES master_storage_options(id) ON DELETE SET NULL,
    color               VARCHAR(100),
    service_mode        VARCHAR(50) NOT NULL DEFAULT 'PICKUP',
    front_image_url     VARCHAR(500),
    back_image_url      VARCHAR(500),
    video_url           VARCHAR(500),
    issue_summary       TEXT,
    estimate_amount     DECIMAL(12, 2),
    final_amount        DECIMAL(12, 2),
    status              VARCHAR(50) NOT NULL DEFAULT 'ORDER_PLACED',
    pickup_address_id   UUID REFERENCES customer_addresses(id) ON DELETE SET NULL,
    pickup_date         DATE,
    pickup_slot_start   TIME,
    pickup_slot_end     TIME,
    estimated_ready_at      TIMESTAMPTZ,
    estimated_duration_hours INT,
    estimated_delivery_at   TIMESTAMPTZ,
    customer_approval       VARCHAR(20),
    device_pin              VARCHAR(20),
    missing_damage_parts    TEXT,
    technician_name         VARCHAR(120),
    technician_code         VARCHAR(40),
    technician_photos       TEXT,
    assigned_pickup_person_id UUID,
    pickup_person_name     VARCHAR(120),
    pickup_person_phone    VARCHAR(30),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_repair_bookings_user ON repair_bookings(customer_user_id);

CREATE TABLE customer_notifications (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_user_id    UUID NOT NULL REFERENCES customer_users(id) ON DELETE CASCADE,
    booking_id          UUID,
    booking_number      VARCHAR(60),
    status_key          VARCHAR(100),
    title               VARCHAR(200) NOT NULL,
    body                TEXT,
    type                VARCHAR(30) DEFAULT 'orders',
    is_read             BOOLEAN NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_customer_notifications_user ON customer_notifications(customer_user_id, created_at DESC);
CREATE INDEX idx_repair_bookings_status ON repair_bookings(status);

CREATE TABLE repair_booking_services (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id          UUID NOT NULL REFERENCES repair_bookings(id) ON DELETE CASCADE,
    repair_service_id   UUID REFERENCES master_repair_services(id) ON DELETE SET NULL,
    service_code        VARCHAR(50),
    service_name        VARCHAR(255),
    estimated_price     DECIMAL(12, 2),
    warranty            VARCHAR(20),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_repair_booking_services_booking ON repair_booking_services(booking_id);

CREATE TABLE repair_booking_events (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    booking_id          UUID NOT NULL REFERENCES repair_bookings(id) ON DELETE CASCADE,
    status              VARCHAR(100) NOT NULL,
    note                TEXT,
    actor               VARCHAR(100),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_repair_booking_events_booking ON repair_booking_events(booking_id);

-- =============================================================================
-- MARKETPLACE CART
-- =============================================================================

CREATE TABLE customer_cart_items (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_user_id    UUID NOT NULL REFERENCES customer_users(id) ON DELETE CASCADE,
    product_id          UUID NOT NULL REFERENCES marketplace_products(id) ON DELETE CASCADE,
    quantity            INT NOT NULL DEFAULT 1 CHECK (quantity > 0),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (customer_user_id, product_id)
);

CREATE INDEX idx_customer_cart_items_user ON customer_cart_items(customer_user_id);

ALTER TABLE marketplace_products ADD COLUMN IF NOT EXISTS condition_label VARCHAR(50);
ALTER TABLE marketplace_products ADD COLUMN IF NOT EXISTS color VARCHAR(100);
ALTER TABLE marketplace_products ADD COLUMN IF NOT EXISTS storage_label VARCHAR(50);
ALTER TABLE marketplace_products ADD COLUMN IF NOT EXISTS network VARCHAR(50);
ALTER TABLE marketplace_products ADD COLUMN IF NOT EXISTS image_url VARCHAR(500);
ALTER TABLE marketplace_products ADD COLUMN IF NOT EXISTS extra_image_urls TEXT;

CREATE TABLE customer_chat_threads (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_user_id    UUID NOT NULL REFERENCES customer_users(id) ON DELETE CASCADE,
    shop_id             UUID REFERENCES shops(id) ON DELETE SET NULL,
    subject             VARCHAR(255),
    last_message_preview VARCHAR(255),
    last_message_at     TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_customer_chat_threads_user ON customer_chat_threads(customer_user_id);

CREATE TABLE customer_chat_messages (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    thread_id           UUID NOT NULL REFERENCES customer_chat_threads(id) ON DELETE CASCADE,
    sender              VARCHAR(50) NOT NULL,
    body                TEXT NOT NULL,
    attachment_url      VARCHAR(500),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_customer_chat_messages_thread ON customer_chat_messages(thread_id);

-- =============================================================================
-- UPDATED_AT TRIGGERS for new tables
-- =============================================================================

CREATE TRIGGER trg_customer_users_updated_at BEFORE UPDATE ON customer_users FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_customer_addresses_updated_at BEFORE UPDATE ON customer_addresses FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_customer_saved_devices_updated_at BEFORE UPDATE ON customer_saved_devices FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_master_device_categories_updated_at BEFORE UPDATE ON master_device_categories FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_master_device_series_updated_at BEFORE UPDATE ON master_device_series FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_master_colors_updated_at BEFORE UPDATE ON master_colors FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_master_model_variants_updated_at BEFORE UPDATE ON master_model_variants FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_master_repair_categories_updated_at BEFORE UPDATE ON master_repair_categories FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_master_screening_questions_updated_at BEFORE UPDATE ON master_screening_questions FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_master_condition_groups_updated_at BEFORE UPDATE ON master_condition_groups FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_master_condition_options_updated_at BEFORE UPDATE ON master_condition_options FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_master_functional_issues_updated_at BEFORE UPDATE ON master_functional_issues FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_master_accessory_options_updated_at BEFORE UPDATE ON master_accessory_options FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_master_warranty_options_updated_at BEFORE UPDATE ON master_warranty_options FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_master_banners_updated_at BEFORE UPDATE ON master_banners FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_master_faq_items_updated_at BEFORE UPDATE ON master_faq_items FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_master_app_content_updated_at BEFORE UPDATE ON master_app_content FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_master_support_contacts_updated_at BEFORE UPDATE ON master_support_contacts FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_shop_pickup_slots_updated_at BEFORE UPDATE ON shop_pickup_slots FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_customer_pickup_orders_updated_at BEFORE UPDATE ON customer_pickup_orders FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_customer_orders_updated_at BEFORE UPDATE ON customer_orders FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_sell_orders_updated_at BEFORE UPDATE ON sell_orders FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_sell_order_quotations_updated_at BEFORE UPDATE ON sell_order_quotations FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_repair_bookings_updated_at BEFORE UPDATE ON repair_bookings FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_customer_cart_items_updated_at BEFORE UPDATE ON customer_cart_items FOR EACH ROW EXECUTE PROCEDURE set_updated_at();
CREATE TRIGGER trg_customer_chat_threads_updated_at BEFORE UPDATE ON customer_chat_threads FOR EACH ROW EXECUTE PROCEDURE set_updated_at();


-- #############################################################################
-- 03_tickets_extended_columns.sql
-- #############################################################################
BEGIN;

ALTER TABLE tickets
    ADD COLUMN IF NOT EXISTS customer_name           VARCHAR(200),
    ADD COLUMN IF NOT EXISTS customer_phone          VARCHAR(30),
    ADD COLUMN IF NOT EXISTS device_display_name     VARCHAR(200),
    ADD COLUMN IF NOT EXISTS device_image_url        VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS repair_services_summary VARCHAR(500),
    ADD COLUMN IF NOT EXISTS price_items_json        TEXT,
    ADD COLUMN IF NOT EXISTS missing_parts_json      TEXT,
    ADD COLUMN IF NOT EXISTS device_photos_json      TEXT,
    ADD COLUMN IF NOT EXISTS device_security_type    VARCHAR(20),
    ADD COLUMN IF NOT EXISTS device_security_value   VARCHAR(255),
    ADD COLUMN IF NOT EXISTS customer_approval       BOOLEAN,
    ADD COLUMN IF NOT EXISTS estimated_ready_at      TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS estimated_delivery_at   TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_tickets_customer_phone     ON tickets(shop_id, customer_phone);
CREATE INDEX IF NOT EXISTS idx_tickets_device_display     ON tickets(shop_id, device_display_name);

COMMIT;


-- #############################################################################
-- 04_auth_otp.sql
-- #############################################################################
BEGIN;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS otp_code VARCHAR(16);

ALTER TABLE customer_users
    ADD COLUMN IF NOT EXISTS otp_code VARCHAR(16);

CREATE INDEX IF NOT EXISTS idx_users_otp_lookup          ON users(email, otp_code);
CREATE INDEX IF NOT EXISTS idx_customer_users_otp_lookup ON customer_users(mobile, otp_code);

COMMIT;


-- #############################################################################
-- 05_shop_owner_extended.sql
-- #############################################################################
BEGIN;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS phone            VARCHAR(50),
    ADD COLUMN IF NOT EXISTS avatar_url       VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS id_proof_url     VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS personal_address TEXT;

ALTER TABLE shops
    ADD COLUMN IF NOT EXISTS owner_user_id          UUID REFERENCES users(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS mobile                 VARCHAR(50),
    ADD COLUMN IF NOT EXISTS district               VARCHAR(120),
    ADD COLUMN IF NOT EXISTS city                   VARCHAR(120),
    ADD COLUMN IF NOT EXISTS state                  VARCHAR(120),
    ADD COLUMN IF NOT EXISTS pincode                VARCHAR(20),
    ADD COLUMN IF NOT EXISTS latitude               NUMERIC(10, 7),
    ADD COLUMN IF NOT EXISTS longitude              NUMERIC(10, 7),
    ADD COLUMN IF NOT EXISTS front_image_url        VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS gst_certificate_url    VARCHAR(1000),
    ADD COLUMN IF NOT EXISTS udyam_certificate_url  VARCHAR(1000);

CREATE INDEX IF NOT EXISTS idx_shops_owner_user_id ON shops(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_shops_pincode       ON shops(pincode);

COMMIT;


-- #############################################################################
-- 06_email_verify_and_shop_meta.sql
-- #############################################################################
BEGIN;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE shops
    ADD COLUMN IF NOT EXISTS shop_type     VARCHAR(80),
    ADD COLUMN IF NOT EXISTS business_type VARCHAR(80),
    ADD COLUMN IF NOT EXISTS billing_type  VARCHAR(40),
    ADD COLUMN IF NOT EXISTS gst_number    VARCHAR(50),
    ADD COLUMN IF NOT EXISTS taluk         VARCHAR(120),
    ADD COLUMN IF NOT EXISTS area          VARCHAR(160),
    ADD COLUMN IF NOT EXISTS street        VARCHAR(200);

UPDATE users SET email_verified = TRUE WHERE email LIKE '%@%' AND email_verified IS NOT TRUE;

COMMIT;


-- #############################################################################
-- 07_owner_profile_extended.sql
-- #############################################################################
BEGIN;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS username          VARCHAR(100),
    ADD COLUMN IF NOT EXISTS pin               VARCHAR(10),
    ADD COLUMN IF NOT EXISTS shop_control      VARCHAR(40),
    ADD COLUMN IF NOT EXISTS secondary_mobile  VARCHAR(50),
    ADD COLUMN IF NOT EXISTS addr_state        VARCHAR(120),
    ADD COLUMN IF NOT EXISTS addr_district     VARCHAR(120),
    ADD COLUMN IF NOT EXISTS addr_taluk        VARCHAR(120),
    ADD COLUMN IF NOT EXISTS addr_area         VARCHAR(160),
    ADD COLUMN IF NOT EXISTS addr_street       VARCHAR(200),
    ADD COLUMN IF NOT EXISTS addr_pincode      VARCHAR(20);

CREATE UNIQUE INDEX IF NOT EXISTS uq_users_shop_username
    ON users(shop_id, username) WHERE username IS NOT NULL;

UPDATE users SET username = email WHERE username IS NULL AND email IS NOT NULL;

COMMIT;


-- #############################################################################
-- 08_drop_unused_profile_fields.sql
-- #############################################################################
BEGIN;

DROP INDEX IF EXISTS uq_users_shop_username;

ALTER TABLE users
    DROP COLUMN IF EXISTS username,
    DROP COLUMN IF EXISTS pin;

ALTER TABLE shops
    DROP COLUMN IF EXISTS shop_type,
    DROP COLUMN IF EXISTS business_type,
    DROP COLUMN IF EXISTS billing_type,
    DROP COLUMN IF EXISTS city;

COMMIT;


-- #############################################################################
-- 09_drop_shop_control.sql
-- #############################################################################
BEGIN;

ALTER TABLE users DROP COLUMN IF EXISTS shop_control;

COMMIT;


-- #############################################################################
-- 10_users_shop_nullable.sql
-- #############################################################################
BEGIN;

ALTER TABLE users ALTER COLUMN shop_id DROP NOT NULL;

UPDATE users SET shop_id = NULL
  WHERE shop_id IN (SELECT id FROM shops WHERE slug = 'admin');

DELETE FROM shops WHERE slug = 'admin';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uq_users_email'
    ) THEN
        ALTER TABLE users ADD CONSTRAINT uq_users_email UNIQUE (email);
    END IF;
END $$;

COMMIT;


-- #############################################################################
-- 11_drop_shop_legacy_fields.sql
-- #############################################################################
BEGIN;

ALTER TABLE shops
    DROP COLUMN IF EXISTS phone,
    DROP COLUMN IF EXISTS hours_text,
    DROP COLUMN IF EXISTS hero_image_url,
    DROP COLUMN IF EXISTS description;

COMMIT;


-- #############################################################################
-- 12_shop_banner_image.sql
-- #############################################################################
BEGIN;

ALTER TABLE shops
    ADD COLUMN IF NOT EXISTS banner_image_url VARCHAR(1000);

COMMIT;


-- #############################################################################
-- 13_marketplace_listings.sql
-- #############################################################################
BEGIN;

CREATE TABLE IF NOT EXISTS marketplace_listings (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    seller_type     VARCHAR(20) NOT NULL,
    seller_id       UUID NOT NULL,
    shop_id         UUID,
    category_id     UUID,
    brand_id        UUID,
    model_id        UUID,
    product_name    VARCHAR(255) NOT NULL,
    product_image   VARCHAR(1000),
    "condition"     VARCHAR(40),
    description     TEXT,
    expected_price  DECIMAL(12, 2) NOT NULL,
    latitude        NUMERIC(10, 7),
    longitude       NUMERIC(10, 7),
    address         TEXT,
    city            VARCHAR(120),
    state           VARCHAR(120),
    pincode         VARCHAR(20),
    status          VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_marketplace_listings_status   ON marketplace_listings(status);
CREATE INDEX IF NOT EXISTS idx_marketplace_listings_seller   ON marketplace_listings(seller_type, seller_id);
CREATE INDEX IF NOT EXISTS idx_marketplace_listings_geo      ON marketplace_listings(latitude, longitude);
CREATE INDEX IF NOT EXISTS idx_marketplace_listings_created  ON marketplace_listings(created_at DESC);

COMMIT;


-- #############################################################################
-- 14_shop_pickup_options.sql
-- #############################################################################
BEGIN;

ALTER TABLE shops
    ADD COLUMN IF NOT EXISTS pickup_from_time    VARCHAR(16),
    ADD COLUMN IF NOT EXISTS pickup_to_time      VARCHAR(16),
    ADD COLUMN IF NOT EXISTS pickup_distance_km  INTEGER,
    ADD COLUMN IF NOT EXISTS pickup_enabled      BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_shops_pickup_enabled ON shops(pickup_enabled) WHERE pickup_enabled = TRUE;

COMMIT;


-- #############################################################################
-- 15_shops_city.sql
-- #############################################################################
BEGIN;

ALTER TABLE shops
    ADD COLUMN IF NOT EXISTS city VARCHAR(255);

COMMIT;


-- #############################################################################
-- 16_technician_attendance.sql
-- #############################################################################
BEGIN;

CREATE TABLE IF NOT EXISTS technician_attendance (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    technician_id    UUID NOT NULL,
    attendance_date  DATE NOT NULL,
    check_in_time    TIME,
    check_out_time   TIME,
    status           VARCHAR(50),
    working_minutes  INTEGER,
    notes            VARCHAR(500),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tech_att_technician_date
    ON technician_attendance(technician_id, attendance_date);

COMMIT;


-- #############################################################################
-- 17_technician_hr_tables.sql
-- #############################################################################
BEGIN;

CREATE TABLE IF NOT EXISTS technician_experience (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    technician_id   UUID NOT NULL,
    shop_name       VARCHAR(255),
    location        VARCHAR(500),
    join_date       DATE NOT NULL,
    relieving_date  DATE,
    working_type    VARCHAR(50),
    last_salary     VARCHAR(50),
    total_service   INTEGER,
    completed_count INTEGER,
    return_count    INTEGER,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tech_exp_technician
    ON technician_experience(technician_id);

CREATE TABLE IF NOT EXISTS technician_leave (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    technician_id UUID NOT NULL,
    start_date    DATE NOT NULL,
    end_date      DATE NOT NULL,
    reason        VARCHAR(500),
    status        VARCHAR(50) NOT NULL,
    requested_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tech_leave_technician
    ON technician_leave(technician_id);

CREATE TABLE IF NOT EXISTS technician_salary_advance (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    technician_id UUID NOT NULL,
    amount        NUMERIC(19,2) NOT NULL,
    advance_date  DATE NOT NULL,
    status        VARCHAR(50) NOT NULL,
    requested_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    notes         VARCHAR(500),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tech_advance_technician
    ON technician_salary_advance(technician_id);

COMMIT;


-- #############################################################################
-- 18_technicians_extended.sql
-- #############################################################################
BEGIN;

ALTER TABLE technicians
    ADD COLUMN IF NOT EXISTS salary_amount         VARCHAR(50),
    ADD COLUMN IF NOT EXISTS salary_period         VARCHAR(50),
    ADD COLUMN IF NOT EXISTS id_verification_type  VARCHAR(50),
    ADD COLUMN IF NOT EXISTS id_number             VARCHAR(100),
    ADD COLUMN IF NOT EXISTS date_of_birth         DATE,
    ADD COLUMN IF NOT EXISTS date_of_join          DATE,
    ADD COLUMN IF NOT EXISTS default_check_in      TIME,
    ADD COLUMN IF NOT EXISTS default_check_out     TIME,
    ADD COLUMN IF NOT EXISTS photo_url             VARCHAR(500);

COMMIT;


-- #############################################################################
-- 19_master_category_brand_mapping.sql
-- #############################################################################
BEGIN;

CREATE TABLE IF NOT EXISTS master_category_brand_mapping (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    category_id UUID NOT NULL,
    brand_id    UUID NOT NULL,
    CONSTRAINT uq_category_brand UNIQUE (category_id, brand_id)
);

CREATE INDEX IF NOT EXISTS idx_mcbm_category_id ON master_category_brand_mapping (category_id);
CREATE INDEX IF NOT EXISTS idx_mcbm_brand_id    ON master_category_brand_mapping (brand_id);

COMMIT;


-- #############################################################################
-- 20_master_device_series_category_brand.sql
-- #############################################################################
BEGIN;

ALTER TABLE master_device_series
    ADD COLUMN IF NOT EXISTS category_brand_id UUID
    REFERENCES master_category_brand_mapping(id) ON DELETE CASCADE;

ALTER TABLE master_device_series
    ADD COLUMN IF NOT EXISTS slug VARCHAR(180);

ALTER TABLE master_device_series
    ALTER COLUMN name TYPE VARCHAR(150);

CREATE INDEX IF NOT EXISTS idx_master_device_series_category_brand
    ON master_device_series (category_brand_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uq_series_cb_slug'
    ) THEN
        ALTER TABLE master_device_series
            ADD CONSTRAINT uq_series_cb_slug UNIQUE (category_brand_id, slug);
    END IF;
END$$;

COMMIT;


-- #############################################################################
-- 21_master_models_slug_category.sql
-- #############################################################################
BEGIN;

ALTER TABLE master_models
    ADD COLUMN IF NOT EXISTS slug VARCHAR(180);

ALTER TABLE master_models
    ADD COLUMN IF NOT EXISTS category VARCHAR(50);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uq_model_series_slug'
    ) THEN
        ALTER TABLE master_models
            ADD CONSTRAINT uq_model_series_slug UNIQUE (series_id, slug);
    END IF;
END$$;

COMMIT;


-- #############################################################################
-- 22_master_device_scoped_taxonomy.sql
-- #############################################################################
BEGIN;

ALTER TABLE master_screening_questions
    ADD COLUMN IF NOT EXISTS device_category_id UUID
    REFERENCES master_device_categories(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_master_screening_questions_category
    ON master_screening_questions (device_category_id);

ALTER TABLE master_condition_groups
    ADD COLUMN IF NOT EXISTS device_category_id UUID
    REFERENCES master_device_categories(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_master_condition_groups_category
    ON master_condition_groups (device_category_id);

ALTER TABLE master_functional_issues
    ADD COLUMN IF NOT EXISTS device_category_id UUID
    REFERENCES master_device_categories(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_master_functional_issues_category
    ON master_functional_issues (device_category_id);

CREATE TABLE IF NOT EXISTS master_device_config_fields (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    device_category_id  UUID REFERENCES master_device_categories(id) ON DELETE CASCADE,
    code                VARCHAR(100),
    name                VARCHAR(150) NOT NULL,
    sort_order          INTEGER NOT NULL DEFAULT 0,
    is_active           BOOLEAN DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_device_config_field_category
    ON master_device_config_fields (device_category_id);

CREATE TABLE IF NOT EXISTS master_device_config_options (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    field_id        UUID NOT NULL REFERENCES master_device_config_fields(id) ON DELETE CASCADE,
    option_value    VARCHAR(255) NOT NULL,
    sort_order      INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_device_config_option_field
    ON master_device_config_options (field_id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_master_device_config_fields_updated_at') THEN
        CREATE TRIGGER trg_master_device_config_fields_updated_at
            BEFORE UPDATE ON master_device_config_fields
            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_master_device_config_options_updated_at') THEN
        CREATE TRIGGER trg_master_device_config_options_updated_at
            BEFORE UPDATE ON master_device_config_options
            FOR EACH ROW EXECUTE FUNCTION set_updated_at();
    END IF;
END$$;

COMMIT;


-- #############################################################################
-- 24_technicians_id_documents.sql
-- #############################################################################
BEGIN;

ALTER TABLE technicians
    ADD COLUMN IF NOT EXISTS aadhar_number     VARCHAR(50),
    ADD COLUMN IF NOT EXISTS aadhar_front_url  VARCHAR(500),
    ADD COLUMN IF NOT EXISTS aadhar_back_url   VARCHAR(500),
    ADD COLUMN IF NOT EXISTS pan_number        VARCHAR(50),
    ADD COLUMN IF NOT EXISTS pan_front_url     VARCHAR(500),
    ADD COLUMN IF NOT EXISTS pan_back_url      VARCHAR(500),
    ADD COLUMN IF NOT EXISTS daily_wage        VARCHAR(50);

COMMIT;
